---
abstract: 'Data::SearchEngine backend for Solr'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Data::SearchEngine::Query: 0
  HTTP::Headers: 0
  HTTP::Response: 0
  Test::More: 0
  WebService::Solr::Response: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-SearchEngine-Solr
requires:
  Clone: 0
  Data::SearchEngine: 0.27
  Data::SearchEngine::Item: 0
  Data::SearchEngine::Paginator: 0
  Data::SearchEngine::Results: 0
  Data::SearchEngine::Results::Spellcheck::Suggestion: 0
  Moose: 0
  Time::HiRes: 0
  WebService::Solr: 0.11
resources:
  homepage: https://github.com/gphat/data-searchengine-solr
  repository: https://github.com/gphat/data-searchengine-solr.git
version: 0.19
