---
abstract: 'Data::SearchEngine backend for Solr'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-SearchEngine-Solr
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.92
  Time::HiRes: 0
  WebService::Solr: 0.08
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
